version: '3'
services:
  web:
    tty: true
    image: nginx
    volumes:
      - ./templates:/usr/share/nginx/html
    ports:
      - "80:80"
    expose:
      - 80
  test:
    tty: true
    build: .
    working_dir: /data
    entrypoint: []
    command: robot-eyes test test.js --base-url=http://web:80
    volumes:
      - ./integrationTests:/data
    depends_on:
      - web
  report:
    tty: true
    build: .
    volumes:
      - ./integrationTests:/data
    working_dir: /data
    ports:
      - 3000:3000
    command: report
  approve:
    tty: true
    build: .
    volumes:
      - ./integrationTests:/data
    working_dir: /data
    command: approve