name: Lint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: yarn install
    - run: yarn lint
      env:
        CI: true
