name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.18.1
          registry-url: https://registry.npmjs.org/
      - name: Define tag
        run: echo tag=`git describe --tags` >> $GITHUB_ENV
      - name: Bump package version
        run: | 
          git config --global user.email ${{ secrets.PUBLISH_EMAIL }}
          git config --global user.name ${{ secrets.PUBLISH_USER_NAME }}
          npm version ${{ env.tag }}
      - name: Push new version to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Login to Docker Hub
        run: docker login -u mercos -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        run: docker build --build-arg ROBOT_EYES_VERSION=${{ env.tag }} -t mercos/robot-eyes:${{ env.tag }} .
      - name: Push version to DockerHub
        run: docker push mercos/robot-eyes:${{ env.tag }}
      - name: Tag Docker Image to latest
        run: docker tag mercos/robot-eyes:${{ env.tag }} mercos/robot-eyes:latest
      - name: Push latest to DockerHub
        run: docker push mercos/robot-eyes:latest
