name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Define tag
        run: echo ::set-env name=TAG::`git describe --tags`
      - name: Yarn Publish
        run: yarn publish --new-version ${TAG}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Login to Docker Hub
        run: docker login -u mercos -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        run: echo ${TAG} && docker build -t mercos/robot-eyes:${TAG} .
      - name: Push version to DockerHub
        run: docker push mercos/robot-eyes:${TAG}
      - name: Tag Docker Image to latest
        run: docker tag mercos/robot-eyes:${TAG} mercos/robot-eyes:latest
      - name: Push latest to DockerHub
        run: docker push mercos/robot-eyes:latest
